package software.kanunnikoff.urlopener.domain.model

/**
 * A named collection of saved links shown on the Home tab.
 *
 * [id] is generated by the persistence layer. New groups use the default value until Room stores
 * them and emits the saved version back through the repository stream.
 */
data class LinkGroup(
    val id: Long = 0L,
    val name: String,
    val description: String,
    val links: List<SavedLink> = emptyList(),
)
